import {generateGeometry,geometryMetadata} from './geometry.mjs';
import {DEFAULT_STATE,validateState,encodeState,decodeState,svgSnapshot} from './state.js';
import {GeometryRenderer,drawCanvas} from './renderer.js';

const $=id=>document.getElementById(id);
let state={...DEFAULT_STATE},geometry=null,renderer=null,canvas=$('geometry-canvas'),worker=null;
let generation=0,renderedGeneration=-1,debounce=0,frameId=0,playing=false,lastFrame=0,lastPaint=0,recording=null,recordTimer=0,recordStream=null,clipFailed=false,clipRestoreMotion=false;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const announce=message=>{$('action-status').textContent=message;};
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const orbit=value=>((value+180)%360+360)%360-180;
try{const incoming=decodeState(location.hash);if(incoming)state=incoming;}catch{announce('The view link was invalid. The default study is loaded.');}

function syncControls(){
 for(const [id,key,scale] of [['complexity','complexity',1],['deformation','deformation',100],['exposure','exposure',100],['yaw','yaw',1],['pitch','pitch',1],['zoom','zoom',100]])$(id).value=String(state[key]*scale);
 $('palette').value=state.palette;$('quality').value=String(state.count);
 $('complexity-value').textContent=String(state.complexity);$('deformation-value').textContent=Math.round(state.deformation*100)+'%';$('exposure-value').textContent=state.exposure.toFixed(1)+'×';
 $('yaw-value').textContent=Math.round(state.yaw)+'°';$('pitch-value').textContent=Math.round(state.pitch)+'°';$('zoom-value').textContent=state.zoom.toFixed(2)+'×';$('seed-value').textContent=String(state.seed);
 document.querySelectorAll('[data-kind]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.kind===state.kind)));
 const meta=geometryMetadata[state.kind];$('model-title').textContent=meta.title;$('model-summary').textContent=meta.description;$('shape-description').textContent=meta.subtitle;
 $('formula').textContent=meta.formula+'\n'+meta.surfaceFormula;$('assumptions').textContent=meta.assumptions;
 const source=meta.sources[0];$('math-source').hidden=!source;if(source)$('math-source').href=source;
 canvas.setAttribute('aria-label',`${meta.title}, ${state.count.toLocaleString()} sampled points. Drag to orbit or use the orbit, elevation and zoom controls. Current orbit ${Math.round(state.yaw)} degrees, elevation ${Math.round(state.pitch)} degrees.`);
}
function draw(){if(renderer&&geometry)renderer.draw(state);}
function setMotion(value){playing=Boolean(value);cancelAnimationFrame(frameId);lastFrame=0;lastPaint=0;$('motion').textContent=playing?'Pause orbit':'Play orbit';$('motion').setAttribute('aria-pressed',String(playing));if(playing)frameId=requestAnimationFrame(animate);}
function animate(time){if(!playing)return;if(!lastFrame)lastFrame=time;const dt=Math.min((time-lastFrame)/1000,.06);lastFrame=time;state.yaw=orbit(state.yaw+dt*7.5);if(time-lastPaint>=(renderer?.mode==='canvas'?50:28)){draw();lastPaint=time;$('yaw').value=String(state.yaw);$('yaw-value').textContent=Math.round(state.yaw)+'°';}frameId=requestAnimationFrame(animate);}
function applyGeometry(result,id){if(id!==generation)return;geometry=result;renderedGeneration=id;renderer?.upload(result);$('point-count').textContent=state.count.toLocaleString()+' computed samples';canvas.removeAttribute('aria-busy');$('canvas-error').hidden=true;draw();}
function generate(){clearTimeout(debounce);const id=++generation;canvas.setAttribute('aria-busy','true');$('point-count').textContent='Calculating structure…';const options={kind:state.kind,count:state.count,complexity:state.complexity,deformation:state.deformation,seed:state.seed};if(worker){worker.postMessage({id,options});return;}setTimeout(()=>{try{applyGeometry(generateGeometry(options),id);}catch(error){if(id===generation){canvas.removeAttribute('aria-busy');announce(error.message);}}},0);}
function requestGeometry(){clearTimeout(debounce);generation++;canvas.setAttribute('aria-busy','true');debounce=setTimeout(generate,100);}
try{worker=new Worker(new URL('./geometry.worker.js',import.meta.url),{type:'module'});worker.onmessage=event=>{const {id,geometry:result,error}=event.data;if(id!==generation)return;if(error){canvas.removeAttribute('aria-busy');announce(error);}else applyGeometry(result,id);};worker.onerror=()=>{worker?.terminate();worker=null;generate();};}catch{worker=null;}

function bindCanvas(){canvas.addEventListener('webglcontextlost',()=>{if(recording){clipFailed=true;stopRecording();}setMotion(false);});let pointer=null;canvas.addEventListener('pointerdown',event=>{if(event.button!==0&&event.pointerType==='mouse')return;setMotion(false);pointer={id:event.pointerId,x:event.clientX,y:event.clientY};canvas.setPointerCapture?.(event.pointerId);});canvas.addEventListener('pointermove',event=>{if(!pointer||pointer.id!==event.pointerId)return;state.yaw=orbit(state.yaw+(event.clientX-pointer.x)*.3);state.pitch=clamp(state.pitch+(event.clientY-pointer.y)*.25,-85,85);pointer.x=event.clientX;pointer.y=event.clientY;syncControls();draw();});const release=()=>{pointer=null;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);canvas.addEventListener('wheel',event=>{if(!event.ctrlKey&&document.activeElement!==canvas)return;event.preventDefault();state.zoom=clamp(state.zoom-event.deltaY*.001,.65,1.5);syncControls();draw();},{passive:false});canvas.addEventListener('keydown',event=>{const actions={ArrowLeft:()=>state.yaw=orbit(state.yaw-5),ArrowRight:()=>state.yaw=orbit(state.yaw+5),ArrowUp:()=>state.pitch=clamp(state.pitch-5,-85,85),ArrowDown:()=>state.pitch=clamp(state.pitch+5,-85,85),'+':()=>state.zoom=clamp(state.zoom+.05,.65,1.5),'-':()=>state.zoom=clamp(state.zoom-.05,.65,1.5)};if(actions[event.key]){event.preventDefault();setMotion(false);actions[event.key]();syncControls();draw();}});}
function startRenderer(forceCanvas=false){renderer=null;try{renderer=new GeometryRenderer(canvas,{forceCanvas,onMode:message=>{$('renderer-status').textContent=message;if(message.startsWith('WebGL')||message.startsWith('Canvas'))$('canvas-error').hidden=true;},onFailure:message=>{announce(message);$('canvas-error').hidden=false;}});bindCanvas();if(geometry){renderer.upload(geometry);draw();}}catch{if(!forceCanvas){const replacement=canvas.cloneNode(false);canvas.replaceWith(replacement);canvas=replacement;startRenderer(true);}else{$('canvas-error').hidden=false;$('renderer-status').textContent='Graphics unavailable';}}}
startRenderer();
$('retry-render').addEventListener('click',()=>{renderer?.dispose();const replacement=canvas.cloneNode(false);canvas.replaceWith(replacement);canvas=replacement;startRenderer(true);if(renderer){$('canvas-error').hidden=true;draw();}});
document.querySelectorAll('[data-kind]').forEach(button=>button.addEventListener('click',()=>{state=validateState({...state,kind:button.dataset.kind});syncControls();requestGeometry();}));
for(const [id,key,scale,rebuild]of [['complexity','complexity',1,true],['deformation','deformation',100,true],['exposure','exposure',100,false],['yaw','yaw',1,false],['pitch','pitch',1,false],['zoom','zoom',100,false]])$(id).addEventListener('input',()=>{state=validateState({...state,[key]:Number($(id).value)/scale});if(id==='yaw'||id==='pitch')setMotion(false);syncControls();if(rebuild)requestGeometry();else draw();});
$('palette').addEventListener('change',()=>{state=validateState({...state,palette:$('palette').value});draw();});
$('quality').addEventListener('change',()=>{state=validateState({...state,count:Number($('quality').value)});syncControls();requestGeometry();});
$('motion').addEventListener('click',()=>setMotion(!playing));
$('remix').addEventListener('click',()=>{const array=new Uint32Array(1);crypto.getRandomValues(array);state.seed=array[0]%100000;syncControls();requestGeometry();});
$('reset').addEventListener('click',()=>{setMotion(false);state={...DEFAULT_STATE};syncControls();requestGeometry();announce('Default study restored.');});
$('cinema').addEventListener('click',()=>{const active=document.body.classList.toggle('cinema-mode');$('cinema').setAttribute('aria-pressed',String(active));$('cinema').textContent=active?'Exit cinema':'Cinema view';requestAnimationFrame(draw);});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('cinema-mode'))$('cinema').click();});
window.addEventListener('resize',draw);
reducedMotion.addEventListener?.('change',event=>{if(event.matches)setMotion(false);});
function saveBlob(blob,name){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function requireGeometry(){if(!geometry||renderedGeneration!==generation||canvas.getAttribute('aria-busy')==='true')throw new Error('Wait for the current structure to finish calculating.');}
async function exportAction(button,fn){button.disabled=true;try{requireGeometry();await fn();}catch(error){announce(error.message||'Export failed. Try a lighter detail setting.');}finally{button.disabled=false;}}
$('export-png').addEventListener('click',()=>exportAction($('export-png'),async()=>{const capture={state:validateState({...state}),geometry};announce('Rendering a fresh 4K image…');await new Promise(resolve=>setTimeout(resolve,20));const output=document.createElement('canvas');output.width=3840;output.height=2160;const ctx=output.getContext('2d');if(!ctx)throw new Error('Image rendering is unavailable in this browser.');drawCanvas(ctx,capture.geometry,capture.state,3840,2160,24000);const blob=await new Promise(resolve=>output.toBlob(resolve,'image/png'));if(!blob)throw new Error('This device could not allocate the 4K export. Try Vector SVG.');saveBlob(blob,`LumenCore-${capture.state.kind}-${capture.state.seed}-4K.png`);output.width=1;output.height=1;announce('4K PNG downloaded. The still uses a crisp vector-style rendering of this geometry.');}));
$('export-svg').addEventListener('click',()=>exportAction($('export-svg'),()=>{saveBlob(new Blob([svgSnapshot(geometry,state)],{type:'image/svg+xml'}),`LumenCore-${state.kind}-${state.seed}.svg`);announce('Vector SVG downloaded. Up to 24,000 samples; it can scale without raster enlargement.');}));
$('save-state').addEventListener('click',()=>{saveBlob(new Blob([JSON.stringify(validateState(state),null,2)],{type:'application/json'}),`LumenCore-${state.kind}-${state.seed}-setup.json`);announce('Setup saved with geometry, camera, palette and seed.');});
$('load-state').addEventListener('change',async()=>{try{const file=$('load-state').files?.[0];if(!file)return;if(file.size>12000)throw new Error('That setup is too large. Choose a saved LumenCore JSON file.');const next=validateState(JSON.parse(await file.text()));setMotion(false);state=next;syncControls();requestGeometry();announce('Saved setup loaded.');}catch(error){announce(error.message||'Invalid setup. Your current study is unchanged.');}finally{$('load-state').value='';}});
$('share-state').addEventListener('click',async()=>{const url=location.origin+location.pathname+encodeState(state);try{await navigator.clipboard.writeText(url);announce('View link copied with this geometry, camera, palette and seed.');}catch{history.replaceState(null,'',encodeState(state));announce('The view is saved in the address bar. Copy that address to share it.');}});
window.addEventListener('hashchange',()=>{try{const next=decodeState(location.hash);if(next){setMotion(false);state=next;syncControls();requestGeometry();}}catch{announce('Invalid view link; the current study was kept.');}});

const clipMime=typeof MediaRecorder==='undefined'?null:['video/webm;codecs=vp9','video/webm;codecs=vp8','video/mp4','video/webm'].find(type=>MediaRecorder.isTypeSupported(type));
if(!clipMime||typeof canvas.captureStream!=='function'){$('record').disabled=true;$('record').textContent='Video recording unavailable here';}
function stopRecording(){clearTimeout(recordTimer);if(recording&&recording.state!=='inactive')recording.stop();}
$('record').addEventListener('click',()=>{if(recording)return;try{requireGeometry();clipRestoreMotion=playing;clipFailed=false;recordStream=canvas.captureStream(30);recording=new MediaRecorder(recordStream,{mimeType:clipMime,videoBitsPerSecond:6000000});const chunks=[];recording.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recording.onerror=()=>{clipFailed=true;announce('This browser could not record the clip. PNG and SVG exports are still available.');stopRecording();};recording.onstop=()=>{recordStream?.getTracks().forEach(track=>track.stop());recordStream=null;recording=null;clearTimeout(recordTimer);$('record').disabled=false;$('record').textContent='Record an 8-second orbit';setMotion(clipRestoreMotion&&!document.hidden);if(!clipFailed&&chunks.length){saveBlob(new Blob(chunks,{type:clipMime}),`LumenCore-${state.kind}-${state.seed}-orbit.${clipMime.includes('mp4')?'mp4':'webm'}`);announce('Orbit clip downloaded.');}else if(!clipFailed)announce('The browser returned an empty clip; try PNG or SVG.');};$('record').disabled=true;$('record').textContent='Recording…';announce('Recording eight seconds at the current canvas size. Keep this tab visible.');setMotion(true);recording.start(250);recordTimer=setTimeout(stopRecording,8000);}catch(error){recordStream?.getTracks().forEach(track=>track.stop());recordStream=null;recording=null;setMotion(clipRestoreMotion&&!document.hidden);$('record').disabled=false;$('record').textContent='Record an 8-second orbit';announce(error.message||'Recording is unavailable.');}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(recording){clipFailed=true;stopRecording();announce('Recording stopped because the tab was hidden.');}setMotion(false);}});
window.addEventListener('pagehide',()=>{if(recording){clipFailed=true;stopRecording();}worker?.terminate();setMotion(false);renderer?.dispose();});

syncControls();generate();
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'get_geometry_study',description:'Read the current mathematical geometry, camera, rendering options and calculation status.',annotations:{readOnlyHint:true,untrustedContentHint:false},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({state:{...state},ready:Boolean(geometry)&&renderedGeneration===generation&&canvas.getAttribute('aria-busy')!=='true',renderer:renderer?.mode||'unavailable',formula:geometryMetadata[state.kind].formula})});
 register({name:'configure_geometry_study',description:'Update the visible geometry and view. Omitted fields keep their current values. Computation may continue after the settings are accepted; use get_geometry_study to check ready.',annotations:{readOnlyHint:false,untrustedContentHint:false},inputSchema:{type:'object',properties:{kind:{type:'string',enum:['trefoil','hopf','gyroid','superformula']},count:{type:'integer',enum:[12000,32000,64000]},complexity:{type:'integer',minimum:1,maximum:5},deformation:{type:'number',minimum:0,maximum:1},seed:{type:'integer',minimum:0,maximum:99999},palette:{type:'string',enum:['duality','aurora','ember','ice']},exposure:{type:'number',minimum:.4,maximum:1.8},yaw:{type:'number',minimum:-180,maximum:180},pitch:{type:'number',minimum:-85,maximum:85},zoom:{type:'number',minimum:.65,maximum:1.5}},additionalProperties:false},execute:async input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(key=>!Object.keys(DEFAULT_STATE).filter(k=>k!=='version').includes(key)))throw new TypeError('Invalid configuration fields.');const next=validateState({...state,...input});setMotion(false);state=next;syncControls();generate();return{status:'settings accepted; geometry computing',state:{...state}};}});
}
