import {PALETTES,projectPoint,colourAt} from './state.js';
export const vertexSource=`attribute vec3 aPosition;attribute float aPhase;uniform vec2 uAngles;uniform float uAspect;uniform float uZoom;uniform float uPixelRatio;uniform float uPointScale;varying float vPhase;varying float vDepth;void main(){float cy=cos(uAngles.x),sy=sin(uAngles.x),cp=cos(uAngles.y),sp=sin(uAngles.y);vec3 p=vec3(cy*aPosition.x+sy*aPosition.z,aPosition.y,-sy*aPosition.x+cy*aPosition.z);p=vec3(p.x,cp*p.y-sp*p.z,sp*p.y+cp*p.z);float camera=5.5-p.z;gl_Position=vec4(2.4*p.x*uZoom*min(1.0,uAspect)/uAspect,2.4*p.y*uZoom*min(1.0,uAspect),0.0,camera);gl_PointSize=clamp(uPointScale*uPixelRatio*6.0/camera,1.0,18.0);vPhase=aPhase;vDepth=(p.z+1.8)/3.6;}`;
export const fragmentSource=`precision mediump float;uniform vec3 uWarm;uniform vec3 uCool;uniform float uExposure;uniform float uOpacity;varying float vPhase;varying float vDepth;void main(){vec2 uv=gl_PointCoord*2.0-1.0;float d=dot(uv,uv);if(d>1.0)discard;float t=0.5+0.5*sin(vPhase*6.2831853);vec3 col=mix(uWarm,uCool,t);float core=exp(-d*10.0);float halo=exp(-d*3.0)*0.18;float alpha=(core+halo)*uOpacity*(0.35+0.65*vDepth)*uExposure;gl_FragColor=vec4(col,alpha);}`;
export class GeometryRenderer{
 constructor(canvas,{onMode=()=>{},onFailure=()=>{},forceCanvas=false}={}){this.canvas=canvas;this.onMode=onMode;this.onFailure=onFailure;this.geometry=null;this.state=null;this.gl=null;this.ctx=null;this.lost=false;this.mode='starting';this.forceCanvas=forceCanvas;this.init();canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();this.lost=true;this.onMode('Graphics paused — restoring context');this.onFailure('Graphics paused. Use Try again for the lighter Canvas view if recovery does not happen.');});canvas.addEventListener('webglcontextrestored',()=>{try{this.lost=false;this.initGL();if(this.geometry)this.upload(this.geometry);if(this.state)this.draw(this.state);}catch{this.onFailure('Graphics could not be restored. Reload to use the fallback view.');}});}
 init(){try{this.gl=this.forceCanvas?null:this.canvas.getContext('webgl',{alpha:false,antialias:false,preserveDrawingBuffer:false,powerPreference:'default'});if(this.gl){this.initGL();return;}}catch{this.gl=null;}this.ctx=this.canvas.getContext('2d');if(!this.ctx)throw new Error('No graphics context available.');this.mode='canvas';this.onMode('Canvas view · up to 8,000 visible samples');}
 initGL(){const gl=this.gl;const compile=(type,src)=>{const shader=gl.createShader(type);if(!shader)throw new Error('Shader allocation failed');gl.shaderSource(shader,src);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(shader);gl.deleteShader(shader);throw new Error(message||'Shader compilation failed');}return shader;};const vs=compile(gl.VERTEX_SHADER,vertexSource),fs=compile(gl.FRAGMENT_SHADER,fragmentSource);this.program=gl.createProgram();gl.attachShader(this.program,vs);gl.attachShader(this.program,fs);gl.linkProgram(this.program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw new Error('Shader linking failed');this.positionBuffer=gl.createBuffer();this.phaseBuffer=gl.createBuffer();this.loc={};for(const key of ['aPosition','aPhase'])this.loc[key]=gl.getAttribLocation(this.program,key);for(const key of ['uAngles','uAspect','uZoom','uPixelRatio','uPointScale','uWarm','uCool','uExposure','uOpacity'])this.loc[key]=gl.getUniformLocation(this.program,key);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.disable(gl.DEPTH_TEST);this.mode='webgl';this.onMode('WebGL · live mathematical geometry');}
 upload(geometry){this.geometry=geometry;if(!this.gl||this.lost)return;const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.positionBuffer);gl.bufferData(gl.ARRAY_BUFFER,geometry.positions,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,this.phaseBuffer);gl.bufferData(gl.ARRAY_BUFFER,geometry.phases,gl.STATIC_DRAW);}
 resize(){const rect=this.canvas.getBoundingClientRect();const ratio=Math.min(window.devicePixelRatio||1,this.mode==='webgl'?1.75:1.25);const width=Math.min(2560,Math.max(1,Math.round(rect.width*ratio))),height=Math.min(2560,Math.max(1,Math.round(rect.height*ratio)));if(this.canvas.width!==width||this.canvas.height!==height){this.canvas.width=width;this.canvas.height=height;}this.ratio=ratio;}
 draw(state){this.state=state;if(!this.geometry||this.lost)return;this.resize();const {width:w,height:h}=this.canvas;if(this.mode==='canvas'){drawCanvas(this.ctx,this.geometry,state,w,h,8000);return;}const gl=this.gl;gl.viewport(0,0,w,h);gl.clearColor(.0196,.0471,.0745,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(this.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.positionBuffer);gl.enableVertexAttribArray(this.loc.aPosition);gl.vertexAttribPointer(this.loc.aPosition,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.phaseBuffer);gl.enableVertexAttribArray(this.loc.aPhase);gl.vertexAttribPointer(this.loc.aPhase,1,gl.FLOAT,false,0,0);gl.uniform2f(this.loc.uAngles,state.yaw*Math.PI/180,state.pitch*Math.PI/180);gl.uniform1f(this.loc.uAspect,w/h);gl.uniform1f(this.loc.uZoom,state.zoom);gl.uniform1f(this.loc.uPixelRatio,this.ratio);gl.uniform1f(this.loc.uPointScale,3.5);gl.uniform3fv(this.loc.uWarm,PALETTES[state.palette][0]);gl.uniform3fv(this.loc.uCool,PALETTES[state.palette][1]);gl.uniform1f(this.loc.uExposure,state.exposure);gl.uniform1f(this.loc.uOpacity,.47*Math.sqrt(32000/this.geometry.phases.length));gl.drawArrays(gl.POINTS,0,this.geometry.phases.length);}
 dispose(){if(this.gl&&!this.lost){this.gl.deleteBuffer(this.positionBuffer);this.gl.deleteBuffer(this.phaseBuffer);this.gl.deleteProgram(this.program);}this.geometry=null;}
}
export function drawCanvas(ctx,geometry,state,width,height,maxPoints=24000){ctx.globalCompositeOperation='source-over';ctx.fillStyle='#050c13';ctx.fillRect(0,0,width,height);ctx.globalCompositeOperation='lighter';const count=geometry.phases.length,step=Math.max(1,Math.ceil(count/maxPoints));const samples=[];for(let i=0;i<count;i+=step){const p=projectPoint(...geometry.positions.subarray(i*3,i*3+3),state,width,height);samples.push({i,...p});}samples.sort((a,b)=>a.depth-b.depth);for(const p of samples){const rgb=colourAt(geometry.phases[p.i],state.palette),depth=(p.depth+1.8)/3.6,radius=Math.max(.65,height/950*(.65+depth));ctx.fillStyle=`rgba(${rgb.join(',')},${Math.min(.9,(.2+.5*depth)*state.exposure).toFixed(3)})`;ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fill();}ctx.globalCompositeOperation='source-over';}
