import {filterFamilies,componentsAfterBreak,humanize} from './portfolio-model.mjs';
const $=id=>document.getElementById(id), el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const repo='https://github.com/robertashworth1986-debug/lumen-core-public/blob/main/';
for(const a of document.querySelectorAll('[data-repo]'))a.href=repo+a.dataset.repo;
const svgEl=(tag,attrs={})=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
async function readData(path){const r=await fetch(path);if(!r.ok)throw new Error('The saved data could not be loaded.');return r.json();}
const [registryLoad,transportLoad,reviewLoad,portfolioLoad]=await Promise.allSettled([readData('data/registry.json'),readData('data/transport.json'),readData('data/review-status.json'),readData('data/portfolio.json')]);
let registry=null,transport=null,selectedGraph=null;
if(registryLoad.status==='fulfilled'){
 registry=registryLoad.value;for(const lane of Object.keys(registry.lanes)){const o=el('option',humanize(lane));o.value=lane;$('lane-filter').append(o);}
 const render=()=>{const matches=filterFamilies(registry.families,$('geometry-search').value,$('lane-filter').value,$('stage-filter').value);$('registry-grid').replaceChildren();for(const f of matches){const card=el('article',undefined,'registry-card');card.append(el('span',humanize(f.lane),'lane'),el('h3',f.label),el('span',humanize(f.status),'badge'));if(f.members)card.append(el('p',f.members.join(' · ')));card.append(el('p',f.claim_boundary||f.located_result||'Candidate in a task-specific evaluation lane. A matched implementation and promotion run are still required.'));if(f.aliases)card.append(el('p','Also indexed as: '+f.aliases.join(', ')));card.append(el('span',f.id,'card-id'));$('registry-grid').append(card);}if(!matches.length)$('registry-grid').append(el('p','No matching forms. Try another name or clear a filter.','empty'));$('registry-status').textContent=`${matches.length} of ${registry.families.length} families · status describes evidence, not a performance ranking`;};
 for(const id of ['geometry-search','lane-filter','stage-filter'])$(id).addEventListener(id==='geometry-search'?'input':'change',render);render();
}else{$('registry-status').textContent='The interactive registry could not load. Use the registry JSON or printable review brief.';}
function graphView(){if(!selectedGraph)return;const edgeValue=$('failed-edge').value;const broken=edgeValue==='none'?null:Number(edgeValue);const state=componentsAfterBreak(selectedGraph,broken);const svg=$('network');svg.replaceChildren();const title=svgEl('title',{id:'network-title'});title.textContent=selectedGraph.label;const desc=svgEl('desc',{id:'network-description'});desc.textContent=`${selectedGraph.nodes.length} nodes, ${selectedGraph.edges.length} intact-design connections. ${broken===null?'No removed connection.':`Connection ${broken+1} removed.`} ${state.sizes.length} connected components.`;svg.append(title,desc);const xy=selectedGraph.nodes.map(([x,y])=>[320+x*450,260-y*450]);selectedGraph.edges.forEach(([a,b],i)=>svg.append(svgEl('line',{x1:xy[a][0],y1:xy[a][1],x2:xy[b][0],y2:xy[b][1],stroke:i===broken?'#f98578':'#78d9df','stroke-width':i===broken?3:1.7,opacity:i===broken?1:.55,...(i===broken?{'stroke-dasharray':'7 7'}:{})})));xy.forEach(([cx,cy],i)=>svg.append(svgEl('circle',{cx,cy,r:3.8,fill:state.labels[i]===0?'#efc387':'#d29fff'})));$('failure-status').textContent=broken===null?'All 64 nodes are connected.':state.connected?'All 64 nodes remain connected after this one break.':`${state.sizes.length} separate components after this break: ${state.sizes.join(' + ')} nodes. Different colours show disconnected groups.`;}
if(transportLoad.status==='fulfilled'){
 transport=transportLoad.value;for(const g of transport.graphs){const o=el('option',g.label+(g.comparison_group!=='controlled_same_terminals'?' · exploratory':''));o.value=g.id;$('graph-select').append(o);}
 const selectGraph=()=>{selectedGraph=transport.graphs.find(g=>g.id===$('graph-select').value);if(!selectedGraph)return;const m=selectedGraph.metrics;$('comparison-group').textContent=selectedGraph.comparison_group==='controlled_same_terminals'?'CONTROLLED · IDENTICAL TERMINALS':'EXPLORATORY · DIFFERENT TERMINALS';$('graph-construction').textContent=selectedGraph.construction;$('graph-metrics').replaceChildren();for(const[label,v]of [['Nodes / edges',`${m.node_count} / ${m.edge_count}`],['Mean DC conductance',m.mean_effective_conductance.toFixed(4)],['Mean path stretch',m.mean_path_stretch.toFixed(3)+'×'],['Wire length (D)',m.total_wire_length.toFixed(3)],['Single-edge deletions',m.single_edge_failures_tested],['Fully connected after break',(100*m.fraction_deletions_preserving_full_connectivity).toFixed(1)+'%']])$('graph-metrics').append(el('dt',label),el('dd',String(v)));$('failed-edge').replaceChildren();const intact=el('option','All connections intact');intact.value='none';$('failed-edge').append(intact);selectedGraph.edges.forEach(([a,b],i)=>{const o=el('option',`Break ${i+1} · node ${a+1} — ${b+1}`);o.value=i;$('failed-edge').append(o);});graphView();};
 $('graph-select').value='square_grid';$('graph-select').addEventListener('change',selectGraph);$('failed-edge').addEventListener('change',graphView);$('reset-edge').addEventListener('click',()=>{$('failed-edge').value='none';graphView();});selectGraph();
 for(const g of transport.graphs.filter(g=>g.comparison_group==='controlled_same_terminals')){const m=g.metrics,tr=el('tr');if(g.id==='square_grid')tr.className='baseline';for(const text of [g.label+(g.id==='square_grid'?' · baseline':''),m.mean_effective_conductance.toFixed(4),m.mean_path_stretch.toFixed(3)+'×',(100*m.fraction_deletions_preserving_full_connectivity).toFixed(1)+'%'])tr.append(el('td',text));$('comparison-body').append(tr);}
 for(const l of transport.limitations)$('transport-limitations').append(el('li',l));
 const square=transport.graphs.find(g=>g.id==='square_grid').metrics,tri=transport.graphs.find(g=>g.id==='triangulated_grid').metrics;$('transport-finding').textContent=`A useful negative result: diagonal connections reduce mean path stretch by ${(100*(1-tri.mean_path_stretch/square.mean_path_stretch)).toFixed(1)}%, but mean conductance falls ${(100*(1-tri.mean_effective_conductance/square.mean_effective_conductance)).toFixed(1)}% against the square grid. With fixed material, extra wire makes every conductor thinner. This result belongs to this model and layout.`;
}else{$('failure-status').textContent='Network data could not load. Download the saved results or open the review brief.';$('graph-select').disabled=true;$('failed-edge').disabled=true;$('reset-edge').disabled=true;}
if(portfolioLoad.status==='fulfilled'){for(const item of portfolioLoad.value){const article=el('article');article.append(el('h3',item.name),el('p',item.stage));const a=el('a','Evidence and next gate ↗');a.href=repo+'docs/PLATFORM_PROOF_AND_COMMERCIALIZATION_MAP.md';article.append(a);$('portfolio-map').append(article);}}
if(reviewLoad.status==='fulfilled'){for(const item of reviewLoad.value.milestones){const p=el('p');p.append(el('strong',item.title+' · '+item.date),document.createTextNode(' — '+item.status));$('institutional-summary').append(p);}}
const failed=[registryLoad,transportLoad,reviewLoad,portfolioLoad].filter(r=>r.status==='rejected').length;if(failed)$('page-status').textContent='Some saved sections could not load. The printable review brief and source links remain available.';
try{const model=await import('./math-models.mjs');for(const kind of ['tetrahedron','cube','octahedron','dodecahedron','icosahedron']){const tile=el('div',undefined,'solid');tile.innerHTML=model.platonicSolidSVG(kind);tile.append(el('span',kind));$('solids').append(tile);}$('cycloid').innerHTML=model.brachistochroneSVG();const d=model.brachistochroneData();$('cycloid-result').textContent=`For a 1 m horizontal run and 1 m drop: cycloid ${d.cycloidTime.toFixed(3)} s; straight incline ${d.straightTime.toFixed(3)} s.`;$('sunflower').innerHTML=model.phyllotaxisSVG();$('branching').innerHTML=model.murrayBranchingSVG();}catch(error){$('page-status').textContent='The equation illustrations could not load. Definitions and source notes remain available.';}
